In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Admin\Desktop\data.csv")
df

URLs  \
0     http://www.bbc.com/news/world-us-canada-414191...   
1     https://www.reuters.com/article/us-filmfestiva...   
2     https://www.nytimes.com/2017/10/09/us/politics...   
3     https://www.reuters.com/article/us-mexico-oil-...   
4     http://www.cnn.com/videos/cnnmoney/2017/10/08/...   
...                                                 ...   
4004  http://beforeitsnews.com/sports/2017/09/trends...   
4005  http://beforeitsnews.com/u-s-politics/2017/10/...   
4006  https://www.activistpost.com/2017/09/ron-paul-...   
4007  https://www.reuters.com/article/us-china-pharm...   
4008  http://beforeitsnews.com/u-s-politics/2017/10/...   

                                               Headline  \
0            Four ways Bob Corker skewered Donald Trump   
1     Linklater's war veteran comedy speaks to moder...   
2     Trump’s Fight With Corker Jeopardizes His Legi...   
3     Egypt's Cheiron wins tie-up with Pemex for Mex...   
4           Jason Aldean opens 'SNL' with Vegas tribute   
...                                                 ...   
4004                                    Trends to Watch   
4005  Trump Jr. Is Soon To Give A 30-Minute Speech F...   
4006        Ron Paul on Trump, Anarchism & the AltRight   
4007  China to accept overseas trial data in bid to ...   
4008  Vice President Mike Pence Leaves NFL Game Beca...   

                                                   Body  Label  
0     Image copyright Getty Images\nOn Sunday mornin...      1  
1     LONDON (Reuters) - “Last Flag Flying”, a comed...      1  
2     The feud broke into public view last week when...      1  
3     MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...      1  
4     Country singer Jason Aldean, who was performin...      1  
...                                                 ...    ...  
4004  Trends to Watch\n% of readers think this story...      0  
4005  Trump Jr. Is Soon To Give A 30-Minute Speech F...      0  
4006                                                NaN      0  
4007  SHANGHAI (Reuters) - China said it plans to ac...      1  
4008  Vice President Mike Pence Leaves NFL Game Beca...      0  

[4009 rows x 4 columns]

In [9]:
df = df.dropna()
df

URLs  \
0     http://www.bbc.com/news/world-us-canada-414191...   
1     https://www.reuters.com/article/us-filmfestiva...   
2     https://www.nytimes.com/2017/10/09/us/politics...   
3     https://www.reuters.com/article/us-mexico-oil-...   
4     http://www.cnn.com/videos/cnnmoney/2017/10/08/...   
...                                                 ...   
4003  http://beforeitsnews.com/u-s-politics/2017/10/...   
4004  http://beforeitsnews.com/sports/2017/09/trends...   
4005  http://beforeitsnews.com/u-s-politics/2017/10/...   
4007  https://www.reuters.com/article/us-china-pharm...   
4008  http://beforeitsnews.com/u-s-politics/2017/10/...   

                                               Headline  \
0            Four ways Bob Corker skewered Donald Trump   
1     Linklater's war veteran comedy speaks to moder...   
2     Trump’s Fight With Corker Jeopardizes His Legi...   
3     Egypt's Cheiron wins tie-up with Pemex for Mex...   
4           Jason Aldean opens 'SNL' with Vegas tribute   
...                                                 ...   
4003  CNN and Globalist Exposed - Steve Quayle and A...   
4004                                    Trends to Watch   
4005  Trump Jr. Is Soon To Give A 30-Minute Speech F...   
4007  China to accept overseas trial data in bid to ...   
4008  Vice President Mike Pence Leaves NFL Game Beca...   

                                                   Body  Label  
0     Image copyright Getty Images\nOn Sunday mornin...      1  
1     LONDON (Reuters) - “Last Flag Flying”, a comed...      1  
2     The feud broke into public view last week when...      1  
3     MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...      1  
4     Country singer Jason Aldean, who was performin...      1  
...                                                 ...    ...  
4003  Vietnam Is in Great Danger, You Must Publish a...      0  
4004  Trends to Watch\n% of readers think this story...      0  
4005  Trump Jr. Is Soon To Give A 30-Minute Speech F...      0  
4007  SHANGHAI (Reuters) - China said it plans to ac...      1  
4008  Vice President Mike Pence Leaves NFL Game Beca...      0  

[3988 rows x 4 columns]

In [30]:
y = df.Label
X = df.drop('Label', axis = 1)
X


URLs  \
0     http://www.bbc.com/news/world-us-canada-414191...   
1     https://www.reuters.com/article/us-filmfestiva...   
2     https://www.nytimes.com/2017/10/09/us/politics...   
3     https://www.reuters.com/article/us-mexico-oil-...   
4     http://www.cnn.com/videos/cnnmoney/2017/10/08/...   
...                                                 ...   
4003  http://beforeitsnews.com/u-s-politics/2017/10/...   
4004  http://beforeitsnews.com/sports/2017/09/trends...   
4005  http://beforeitsnews.com/u-s-politics/2017/10/...   
4007  https://www.reuters.com/article/us-china-pharm...   
4008  http://beforeitsnews.com/u-s-politics/2017/10/...   

                                               Headline  \
0            Four ways Bob Corker skewered Donald Trump   
1     Linklater's war veteran comedy speaks to moder...   
2     Trump’s Fight With Corker Jeopardizes His Legi...   
3     Egypt's Cheiron wins tie-up with Pemex for Mex...   
4           Jason Aldean opens 'SNL' with Vegas tribute   
...                                                 ...   
4003  CNN and Globalist Exposed - Steve Quayle and A...   
4004                                    Trends to Watch   
4005  Trump Jr. Is Soon To Give A 30-Minute Speech F...   
4007  China to accept overseas trial data in bid to ...   
4008  Vice President Mike Pence Leaves NFL Game Beca...   

                                                   Body  
0     Image copyright Getty Images\nOn Sunday mornin...  
1     LONDON (Reuters) - “Last Flag Flying”, a comed...  
2     The feud broke into public view last week when...  
3     MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...  
4     Country singer Jason Aldean, who was performin...  
...                                                 ...  
4003  Vietnam Is in Great Danger, You Must Publish a...  
4004  Trends to Watch\n% of readers think this story...  
4005  Trump Jr. Is Soon To Give A 30-Minute Speech F...  
4007  SHANGHAI (Reuters) - China said it plans to ac...  
4008  Vice President Mike Pence Leaves NFL Game Beca...  

[3988 rows x 3 columns]

In [13]:
import tensorflow as tf

In [45]:
voc_size = 30000

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [31]:
Messages = X.copy()
messages = Messages.reset_index()
messages

index                                               URLs  \
0         0  http://www.bbc.com/news/world-us-canada-414191...   
1         1  https://www.reuters.com/article/us-filmfestiva...   
2         2  https://www.nytimes.com/2017/10/09/us/politics...   
3         3  https://www.reuters.com/article/us-mexico-oil-...   
4         4  http://www.cnn.com/videos/cnnmoney/2017/10/08/...   
...     ...                                                ...   
3983   4003  http://beforeitsnews.com/u-s-politics/2017/10/...   
3984   4004  http://beforeitsnews.com/sports/2017/09/trends...   
3985   4005  http://beforeitsnews.com/u-s-politics/2017/10/...   
3986   4007  https://www.reuters.com/article/us-china-pharm...   
3987   4008  http://beforeitsnews.com/u-s-politics/2017/10/...   

                                               Headline  \
0            Four ways Bob Corker skewered Donald Trump   
1     Linklater's war veteran comedy speaks to moder...   
2     Trump’s Fight With Corker Jeopardizes His Legi...   
3     Egypt's Cheiron wins tie-up with Pemex for Mex...   
4           Jason Aldean opens 'SNL' with Vegas tribute   
...                                                 ...   
3983  CNN and Globalist Exposed - Steve Quayle and A...   
3984                                    Trends to Watch   
3985  Trump Jr. Is Soon To Give A 30-Minute Speech F...   
3986  China to accept overseas trial data in bid to ...   
3987  Vice President Mike Pence Leaves NFL Game Beca...   

                                                   Body  
0     Image copyright Getty Images\nOn Sunday mornin...  
1     LONDON (Reuters) - “Last Flag Flying”, a comed...  
2     The feud broke into public view last week when...  
3     MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...  
4     Country singer Jason Aldean, who was performin...  
...                                                 ...  
3983  Vietnam Is in Great Danger, You Must Publish a...  
3984  Trends to Watch\n% of readers think this story...  
3985  Trump Jr. Is Soon To Give A 30-Minute Speech F...  
3986  SHANGHAI (Reuters) - China said it plans to ac...  
3987  Vice President Mike Pence Leaves NFL Game Beca...  

[3988 rows x 4 columns]

In [21]:
import nltk
import re
from nltk.corpus import stopwords

In [27]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [33]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    news = re.sub('[^a-zA-Z]', ' ', messages['Body'][i])
    news = news.lower()
    news = news.split()
    
    news = [ps.stem(word) for word in news if not word in stopwords.words('english')]
    news = ' '.join(news)
    corpus.append(news)

In [64]:
corpus

['imag copyright getti imag sunday morn donald trump went twitter tirad member parti exactli huge news far first time presid turn rhetor cannon rank time howev attack particularli bite person essenti call tennesse senat bob corker chair power senat foreign relat committe coward run elect said mr corker beg presid endors refus give wrongli claim mr corker support iranian nuclear agreement polit accomplish unlik colleagu mr corker free worri immedi polit futur hold tongu skip twitter post senbobcork shame white hous becom adult day care center someon obvious miss shift morn senat bob corker senbobcork octob report end though spoke new york time realli let presid four choic quot tennesse senat interview time particularli damn know presid tweet thing true know everyon know realli sugarcoat one mr corker flat say presid liar everyon know senat particular challeng mr trump insist unsuccess plead endors accus much broader mr corker presid use someth akin alli tennessean mr trump short list vi

In [ ]:
onehot_rep=[one_hot(words, voc_size)for words in corpus]
onehot_rep

In [50]:
sent_length=1000
embedded = pad_sequences(onehot_rep,padding='pre',maxlen=sent_length)
print(embedded)

[[    0     0     0 ... 27648  1043  3208]
 [    0     0     0 ...  8083 27245  6675]
 [    0     0     0 ... 16553  2145  8094]
 ...
 [    0     0     0 ...  8514  8818 10369]
 [    0     0     0 ... 20867 24275  3844]
 [    0     0     0 ...   834  8189 28933]]


In [51]:
embedding_vector_features = 100
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features, input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 1000, 100)         3000000   
                                                                 
 lstm (LSTM)                 (None, 100)               80400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 3,080,501
Trainable params: 3,080,501
Non-trainable params: 0
_________________________________________________________________
None


In [53]:
import numpy as np
X_final=np.array(embedded)
y_final = np.array(y)
X_final.shape, y_final.shape

((3988, 1000), (3988,))

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.2, random_state=42)

In [55]:
model.fit(X_train, y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
50/50 [==============================] - 132s 3s/step - loss: 0.4058 - accuracy: 0.8066 - val_loss: 0.1326 - val_accuracy: 0.9511
Epoch 2/10
50/50 [==============================] - 132s 3s/step - loss: 0.0507 - accuracy: 0.9846 - val_loss: 0.0735 - val_accuracy: 0.9724
Epoch 3/10
50/50 [==============================] - 134s 3s/step - loss: 0.0152 - accuracy: 0.9969 - val_loss: 0.0615 - val_accuracy: 0.9799
Epoch 4/10
50/50 [==============================] - 134s 3s/step - loss: 0.0034 - accuracy: 0.9997 - val_loss: 0.0553 - val_accuracy: 0.9862
Epoch 5/10
50/50 [==============================] - 137s 3s/step - loss: 0.0015 - accuracy: 1.0000 - val_loss: 0.0657 - val_accuracy: 0.9837
Epoch 6/10
50/50 [==============================] - 138s 3s/step - loss: 9.1205e-04 - accuracy: 1.0000 - val_loss: 0.0706 - val_accuracy: 0.9825
Epoch 7/10
50/50 [==============================] - 136s 3s/step - loss: 6.4024e-04 - accuracy: 1.0000 - val_loss: 0.0787 - val_accuracy: 0.9850
Epoch

In [65]:
pred = model.predict(X_test)
pred = pred.round()
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)
print('accuracy: ', acc*100, '%')
#from sklearn.metrics import confusion_matrix
#confusion_matrix(y_test, pred)

25/25 [==============================] - 6s 221ms/step
accuracy:  98.24561403508771 %
